server:
  port: 8998


spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://localhost:3306/formality?useSSL=false
    username: user
    password: emailsemotions
    initialization-mode: ALWAYS

---
# spring:
#   config:
#     activate:
#       on-profile: docker
#   zipkin:
#     baseUrl: http://tracing-server:9411
# server:
#   port: 8083
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://discovery-server:8761/eureka/