spring:
  config:
    activate:
      on-profile: default
info:
  app:
    uuid: ${app_uuid}
  tags:
    name: ${spring.application.name}
    app-id: ${info.app.uuid}

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${app_uuid}
    # Lease Reneval and Expiration times - to unregister in eureka
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://dbusers:3308/users?useSSL=false
    username: user
    password: emailsemotions
    initialization-mode: ALWAYS
#   zipkin:
#     baseUrl: http://tracing-server:9411
# server:
#   port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
