spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
    # Lease Reneval and Expiration times - to unregister in eureka
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true
---
# spring:
#   config:
#     activate:
#       on-profile: docker
#   zipkin:
#     baseUrl: http://tracing-server:9411
# server:
#   port: 8083
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://discovery-server:8761/eureka/